feat: [DCS-247] add count_all_space and percent_all_space functions
datachecks/dcs-core pull request #254
Opened 2024-09-05 18:43 UTC by Ksaurav3380

### Fixes/Implements #

## Description

Validity function for count all space and percent all space

## Type of change

Delete irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [x] Locally Tested
- [ ] Needs Testing From Production

2024-09-05 18:46 UTC, Ksaurav3380 commented
fix: module error

2024-09-07 17:28 UTC, subhankarb requested changes

2024-09-07 17:28 UTC, subhankarb commented on dcs_core/core/common/models/validation.py
> +    COUNT_NULL_KEYWORD = "count_null_keyword"
This PR did not implemented `COUNT_NULL_KEYWORD`

2024-09-07 17:28 UTC, subhankarb commented on dcs_core/core/validation/completeness_validation.py
> +class CountEmptyStringValidation(Validation):
This class has not been used. We can drop the class.

2024-09-07 17:28 UTC, subhankarb commented on dcs_core/core/datasource/sql_datasource.py
> +    ) -> int:
This function can return both int and float

2024-09-07 17:28 UTC, subhankarb commented on dcs_core/core/validation/completeness_validation.py
> +            return self.data_source.query_get_empty_string_count(
This has not been implemented for search data source. We should use `notImplementedError`

2024-09-09 07:49 UTC, subhankarb approved these changes

2024-09-09 07:50 UTC, merged